//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFBS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class R_C_N
    {
        public decimal ID_COMPETENCIA { get; set; }
        public decimal NOTA_ENCUESTA { get; set; }
    
        public virtual NIVEL NIVEL { get; set; }
    }
}
